blank_issues_enabled: false
contact_links:
  - name: "💬 General Question or Discussion"
    url: "https://github.com/Ciprian-LocalPulse/open-fraud-intelligence/discussions"
    about: "If you want to ask a question or discuss cybersec trends, please use GitHub Discussions instead."